prova: compito.o liste.o tipo.o
		g++ -o ver compito.cc liste.cc tipo.cc
		
compito.o: liste.h
		g++ -c compito.cc
		
liste.o: liste.cc liste.h
		g++ -c liste.cc
		
tipo.o: tipo.cc tipo.h
		g++ -c tipo.cc
		
		
