152806: compito.cc File Reference
compito.cc File Reference
#include <iostream>
#include <fstream>
#include <string.h>
#include "liste.h"
#include "tipo.h"
Functions
void agenda (lista &agenda, tipo_inf a)
void stampa (lista agenda)
void quanti (lista Agenda, tipo_inf a)
int main ()
Function Documentation
agenda()
void agenda (lista & agenda, tipo_inf a)
Aggiungeun appuntamento all'agenda
Parameters
lista& agenda
tipo_inf a
Definition at line 19 of file compito.cc.
References new_elem(), ord_insert_elem(), print(), and search().
Referenced by main(), and stampa().
main()
int main ()
Definition at line 62 of file compito.cc.
References agenda(), tipo_inf::data, tipo_inf::descr, tipo_inf::oraFine, tipo_inf::oraInizio, and stampa().
quanti()
void quanti (lista Agenda, tipo_inf a)
Definition at line 43 of file compito.cc.
References tipo_inf::data, head(), tipo_inf::oraInizio, print(), and tail().
stampa()
void stampa (lista agenda)
Funzione per stampare l'agenda Si sfruttano le primitive delle liste per stampare l'agenda
Definition at line 35 of file compito.cc.
References agenda(), head(), print(), and tail().
Referenced by main().