152806: liste.cc File Reference
liste.cc File Reference
#include <iostream>
#include <cstring>
#include "tipo.h"
#include "liste.h"
Functions
tipo_inf head (lista p)
elem * search (lista l, tipo_inf v)
elem * new_elem (tipo_inf inf)
lista tail (lista p)
lista prev (lista p)
lista insert_elem (lista l, elem *e)
lista delete_elem (lista l, elem *e)
lista ord_insert_elem (lista l, elem *e)
Function Documentation
delete_elem()
lista delete_elem (lista l, elem * e)
Definition at line 45 of file liste.cc.
References elem::prev, prev(), and elem::pun.
head()
tipo_inf head (lista p)
Definition at line 14 of file liste.cc.
References elem::inf.
Referenced by ord_insert_elem(), quanti(), search(), and stampa().
insert_elem()
lista insert_elem (lista l, elem * e)
Definition at line 37 of file liste.cc.
References elem::prev, and elem::pun.
Referenced by ord_insert_elem().
new_elem()
elem* new_elem (tipo_inf inf)
Definition at line 25 of file liste.cc.
References copy(), elem::inf, elem::prev, and elem::pun.
Referenced by agenda().
ord_insert_elem()
lista ord_insert_elem (lista l, elem * e)
Definition at line 57 of file liste.cc.
References compare(), head(), elem::inf, insert_elem(), elem::prev, elem::pun, and tail().
Referenced by agenda().
prev()
lista prev (lista p)
Definition at line 35 of file liste.cc.
References elem::prev.
Referenced by delete_elem().
search()
elem* search (lista l, tipo_inf v)
Definition at line 16 of file liste.cc.
References compare(), head(), and tail().
Referenced by agenda().
tail()
lista tail (lista p)
Definition at line 34 of file liste.cc.
References elem::pun.
Referenced by ord_insert_elem(), quanti(), search(), and stampa().