152806: liste.h File Reference
liste.h File Reference
#include "tipo.h"
Classes
struct elem
Typedefs
typedef elem * lista
Functions
lista tail (lista)
lista prev (lista)
lista insert_elem (lista, elem *)
lista delete_elem (lista, elem *)
lista ord_insert_elem (lista, elem *)
tipo_inf head (lista)
elem * new_elem (tipo_inf)
elem * search (lista, tipo_inf)
Typedef Documentation
lista
typedef elem* lista
Definition at line 17 of file liste.h.
Function Documentation
delete_elem()
lista delete_elem (lista , elem *)
Definition at line 45 of file liste.cc.
References elem::prev, prev(), and elem::pun.
head()
tipo_inf head (lista)
Definition at line 14 of file liste.cc.
References elem::inf.
Referenced by ord_insert_elem(), quanti(), search(), and stampa().
insert_elem()
lista insert_elem (lista , elem *)
Definition at line 37 of file liste.cc.
References elem::prev, and elem::pun.
Referenced by ord_insert_elem().
new_elem()
elem* new_elem (tipo_inf)
Definition at line 25 of file liste.cc.
References copy(), elem::inf, elem::prev, and elem::pun.
Referenced by agenda().
ord_insert_elem()
lista ord_insert_elem (lista , elem *)
Definition at line 57 of file liste.cc.
References compare(), head(), elem::inf, insert_elem(), elem::prev, elem::pun, and tail().
Referenced by agenda().
prev()
lista prev (lista)
Definition at line 35 of file liste.cc.
References elem::prev.
Referenced by delete_elem().
search()
elem* search (lista , tipo_inf)
Definition at line 16 of file liste.cc.
References compare(), head(), and tail().
Referenced by agenda().
tail()
lista tail (lista)
Definition at line 34 of file liste.cc.
References elem::pun.
Referenced by ord_insert_elem(), quanti(), search(), and stampa().