152806: tipo.cc File Reference
tipo.cc File Reference
#include "tipo.h"
#include <string.h>
#include <iostream>
Functions
int compare (tipo_inf a1, tipo_inf a2)
void copy (tipo_inf &a1, tipo_inf a2)
void print (tipo_inf a)
Function Documentation
compare()
int compare (tipo_inf a1, tipo_inf a2)
Definition at line 7 of file tipo.cc.
References tipo_inf::data, and tipo_inf::oraInizio.
Referenced by ord_insert_elem(), and search().
copy()
void copy (tipo_inf & a1, tipo_inf a2)
Definition at line 14 of file tipo.cc.
References tipo_inf::data, tipo_inf::descr, tipo_inf::oraFine, and tipo_inf::oraInizio.
Referenced by new_elem().
print()
void print (tipo_inf a)
Definition at line 21 of file tipo.cc.
References tipo_inf::data, tipo_inf::descr, tipo_inf::oraFine, and tipo_inf::oraInizio.
Referenced by agenda(), quanti(), and stampa().