152806: tipo.h File Reference
tipo.h File Reference
Classes
struct tipo_inf
Typedefs
typedef tipo_inf appuntamento
Functions
int compare (tipo_inf, tipo_inf)
void copy (tipo_inf &, tipo_inf)
void print (tipo_inf)
Typedef Documentation
appuntamento
typedef tipo_inf appuntamento
Definition at line 13 of file tipo.h.
Function Documentation
compare()
int compare (tipo_inf , tipo_inf)
Definition at line 7 of file tipo.cc.
References tipo_inf::data, and tipo_inf::oraInizio.
Referenced by ord_insert_elem(), and search().
copy()
void copy (tipo_inf & , tipo_inf)
Definition at line 14 of file tipo.cc.
References tipo_inf::data, tipo_inf::descr, tipo_inf::oraFine, and tipo_inf::oraInizio.
Referenced by new_elem().
print()
void print (tipo_inf)
Definition at line 21 of file tipo.cc.
References tipo_inf::data, tipo_inf::descr, tipo_inf::oraFine, and tipo_inf::oraInizio.
Referenced by agenda(), quanti(), and stampa().